In [1]:
import numpy as np

In [2]:
x1 = np.random.randint(10, size=8)

In [3]:
print(x1)

[9 1 6 3 4 0 9 1]


In [4]:
x2 = np.random.randint(10, size=(3, 4))

In [5]:
print(x2)

[[6 2 7 0]
 [7 9 6 9]
 [6 8 4 8]]


In [6]:
print(x2.shape)

(3, 4)


In [17]:
x3 = np.random.randint(10, size=(3, 4, 5))

In [18]:
print(x3)

[[[3 0 5 2 2]
  [3 1 9 0 6]
  [9 6 2 4 8]
  [8 4 9 2 6]]

 [[2 2 7 3 8]
  [2 2 0 7 5]
  [8 2 0 7 6]
  [2 8 3 8 5]]

 [[4 1 2 0 1]
  [7 8 1 6 7]
  [8 1 1 7 1]
  [0 3 6 3 7]]]


In [20]:
print(x3[0])

[[3 0 5 2 2]
 [3 1 9 0 6]
 [9 6 2 4 8]
 [8 4 9 2 6]]


In [23]:
print(x3[0].shape)

(4, 5)


In [24]:
print(x3.dtype)

int32


In [25]:
print(x2)

[[6 2 4 2]
 [7 4 9 0]
 [3 3 9 9]]


In [28]:
print(x2[0,0:3])

[6 2 4]


In [30]:
a_list=[1, 2, 3, 4, 5, 7, 7, 1]

In [31]:
a_np=np.array(a_list)

In [32]:
a_np

array([1, 2, 3, 4, 5, 7, 7, 1])

In [34]:
type(a_np)

numpy.ndarray